version: '2'
services: 
  php-apache:
    build:
      context: .
    ports:
      - 80:80
    volumes: 
      - ./www:/var/www/html
    environment:
      TITLE: "SPAQ LOCAL "
      SUBTITLE: "SPAQ storage  "
      THUIS: "http://localhost/spaq/"
      TZ: "Europe/Amsterdam"

  myflaskwebservice:
    build:
      context: ./flaskpython
    ports:
      - 8087:5000
    # environment: 
      # ENV STATIC_URL /static
      # ENV STATIC_PATH /var/www/app/static  
    volumes:
      - ./flaskpython:/usr/src/app
