version: '2'
services: 
  php-apache:
    build:
      context: .
    ports:
      - 80:80
    volumes: 
      - ./www:/var/www/html
    environment:
      TITLE: "SPAQ LOCAL "
      SUBTITLE: "SPAQ storage  "
      THUIS: "http://localhost/spaq/"
      TZ: "Europe/Amsterdam"

