version: '2'
services: 

  limesurvey:
    image: acspri/limesurvey
    ports:
      - 8085:80
    environment:
      LIMESURVEY_DB_PASSWORD: example
      LIMESURVEY_ADMIN_USER: admin
      LIMESURVEY_ADMIN_PASSWORD: password
      LIMESURVEY_ADMIN_NAME: Lime Administrator
      LIMESURVEY_ADMIN_EMAIL: lime@lime.lime

  mysql:
    image: mariadb
    volumes: 
      - transdb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  myflaskwebservice:
    build:
      context: ./flaskpython
    ports:
      - 8087:5000
    # environment: 
      # ENV STATIC_URL /static
      # ENV STATIC_PATH /var/www/app/static  
    volumes:
      - ./flaskpython:/usr/src/app

  php-apache:
    build:
      context: .
    ports:
      - 80:80
    volumes: 
      - ./www:/var/www/html
    environment:
      TITLE: "SPAQ LOCAL "
      SUBTITLE: "SPAQ storage  "
      THUIS: "http://localhost/spaq/"
      TZ: "Europe/Amsterdam"      

volumes:
  transdb:       