version: '2'
services: 

    limesurvey:
        image: acspri/limesurvey:5.0.5
        ports:
            - 8085:80
        environment:
            LIMESURVEY_DB_PASSWORD: example
            LIMESURVEY_ADMIN_USER: admin
            LIMESURVEY_ADMIN_PASSWORD: password
            LIMESURVEY_ADMIN_NAME: Lime Administrator
            LIMESURVEY_ADMIN_EMAIL: lime@lime.lime

    mysql:
        image: mariadb:10.5
        volumes: 
            - mysqldb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: example



    flaskie:
        build:
            context: ./flask
            dockerfile: Dockerfile.dev
        # dockerfile: Dockerfile.test
        ports:
            - 8087:5000
        # environment: 
        # ENV STATIC_URL /static
        # ENV STATIC_PATH /var/www/app/static  
        volumes:
            - ./flask:/usr/src/app
            - ./storage:/usr/src/app/static/store

    # conversion of audiofiles
    watchdog:
        build:
            context: ./watchdog
            dockerfile: Dockerfile
        
        ports:
            - 8888:5000

        volumes:
            - ./watchdog:/usr/src/app
            - ./storage:/usr/src/app/static/store

    php-apache:
        build:
            context: .
        ports:
            - 80:80
        volumes: 
            - ./www:/var/www/html
        environment:
            TITLE: "SPAQ LOCAL "
            SUBTITLE: "SPAQ storage  "
            THUIS: "http://localhost/spaq/"
            TZ: "Europe/Amsterdam"      

volumes:
  mysqldb:       